# Generated by Django 4.1.3 on 2022-11-15 14:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_name', models.CharField(max_length=50)),
                ('branch_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('hostel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('hostel_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('roll_no', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=30)),
                ('room_no', models.IntegerField()),
                ('phone_number', models.CharField(default='+91', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth_App.branch')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth_App.hostel')),
            ],
        ),
    ]
