# Generated by Django 4.1 on 2022-11-04 19:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_App', '0002_alter_branch_branch_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('hostel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('hostel_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('roll_no', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=30)),
                ('room_no', models.IntegerField()),
                ('phone_no', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)])),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth_App.branch')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth_App.hostel')),
            ],
        ),
    ]
