# Generated by Django 4.1.3 on 2022-11-06 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_App', '0005_alter_student_phone_number'),
        ('ActivityManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfActivtiy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('act', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField()),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth_App.student')),
            ],
        ),
    ]
