# Generated by Django 4.1.3 on 2022-11-10 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityManager', '0003_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='user',
        ),
    ]
